#!/bin/sh
echo "Would you like to: "
echo "1: Compare two ps log files manually saved? (Please run xcreatepslog twice first)"
echo "2: Compare current ps log vs baseline ps log saved beforehand (Please run xsavebaseline first)"
echo "3: Save ps log with current timestamp"



